# Generated by Django 3.2.6 on 2021-08-18 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deletion_date', models.DateTimeField(null=True)),
                ('show_in_pos', models.BooleanField()),
                ('show_in_menu_configuration', models.BooleanField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_children', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('fiscal_name', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('deletion_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('fiscal_name', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('deletion_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deletion_date', models.DateTimeField(null=True)),
                ('show_in_pos', models.BooleanField()),
                ('show_in_menu_configuration', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deletion_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('needsPrinting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PreparationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deletion_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_sold_as_principal_product', models.BooleanField()),
                ('is_sold_as_added', models.BooleanField()),
                ('is_sold_by_weight', models.BooleanField()),
                ('code_PLU', models.CharField(max_length=100)),
                ('allergens', models.ManyToManyField(to='core.Allergen')),
                ('categories', models.ManyToManyField(to='core.Category')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.family')),
                ('preparation_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.preparationorder')),
                ('preparation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.preparationtype')),
            ],
        ),
        migrations.CreateModel(
            name='SaleCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.building')),
            ],
        ),
        migrations.CreateModel(
            name='SaleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('sale_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_locations', to='core.salecenter')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_business_name', models.CharField(max_length=100)),
                ('customer_fiscal_name', models.CharField(max_length=100)),
                ('customer_cif', models.CharField(max_length=100)),
                ('customer_telephone', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=100)),
                ('customer_street', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_region', models.CharField(max_length=100)),
                ('customer_zip_code', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('discount_rate', models.FloatField()),
                ('discount_total', models.FloatField()),
                ('cash_discount', models.FloatField()),
                ('gross', models.FloatField()),
                ('net', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('sale_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.salelocation')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.company')),
                ('apply_equivalence_charge', models.BooleanField()),
            ],
            bases=('core.company',),
        ),
        migrations.CreateModel(
            name='TicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('discount_total', models.FloatField()),
                ('status', models.CharField(choices=[('CREATED', 'CREATED')], max_length=20)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax', models.FloatField()),
                ('gross', models.FloatField()),
                ('sales_tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.salestax')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_lines', to='core.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.FloatField()),
                ('added', models.FloatField()),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='core.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sales_tax',
            field=models.ManyToManyField(to='core.SalesTax'),
        ),
        migrations.AddField(
            model_name='family',
            name='major_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='core.majorgroup'),
        ),
        migrations.AddField(
            model_name='family',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_families', to='core.family'),
        ),
    ]
